name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Locate Project and Build APK
        run: |
          # Find directory containing pubspec.yaml
          PUB_PATH=$(find . -name "pubspec.yaml" | head -n 1)
          TARGET_DIR=$(dirname "$PUB_PATH")
          echo "Building Flutter project in: $TARGET_DIR"
          
          cd "$TARGET_DIR"
          flutter pub get
          flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/app/outputs/flutter-apk/app-debug.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/app/outputs/flutter-apk/app-debug.apk"
